name: Generate and Deploy GitHub Pages

on:
  push:
    paths:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install markdown beautifulsoup4

      - name: Generate HTML from README.md
        run: python generate_pages.py


      - name: Ensure Clean Working Tree & Switch to `gh-pages`
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure the latest `gh-pages` branch is fetched
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages

          # Copy the new index.html without removing it
          cp index.html index.html.new

          # Ensure `.nojekyll` exists
          touch .nojekyll

          # Add changes
          mv index.html.new index.html
          git add .nojekyll index.html
          git commit -m "Auto-update index.html from README.md" || echo "No changes to commit"
          git push origin gh-pages --force


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout `gh-pages` Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          keep_files: true
          force_orphan: true
