name: Generate and Deploy HTML from README

on:
  push:
    paths:
      - 'README.md'
    branches:
      - main # Only triggers on pushes to main
  workflow_dispatch: # Manually trigger the workflow

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 markdown

    - name: Generate HTML
      run: python generate_html.py

    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Copy index.html to gh-pages
      run: |
        cp index.html ./

    - name: Configure Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Commit and push changes to gh-pages
      run: |
        git add index.html
        git commit -m "Update index.html from README.md change or manual trigger"
        git push origin gh-pages